create extension if not exists pgcrypto;

create table if not exists public.model_profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  identity_gender text not null,
  profile_payload jsonb not null,
  photo_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_outputs (
  id uuid primary key default gen_random_uuid(),
  model_profile_id uuid not null references public.model_profiles(id) on delete cascade,
  draft_output jsonb not null,
  approved_output jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.feedback_entries (
  id uuid primary key default gen_random_uuid(),
  model_profile_id uuid not null references public.model_profiles(id) on delete cascade,
  brand_output_id uuid not null references public.brand_outputs(id) on delete cascade,
  field_path text not null,
  before_value text not null,
  after_value text not null,
  reason text not null,
  scope text not null check (scope in ('global', 'model', 'archetype')),
  review_status text not null default 'pending' check (review_status in ('pending', 'approved', 'rejected')),
  archetype_key text not null default '',
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.health_checks (
  id bigint generated by default as identity primary key,
  source text not null,
  checked_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.model_profiles enable row level security;
alter table public.brand_outputs enable row level security;
alter table public.feedback_entries enable row level security;
alter table public.health_checks enable row level security;
alter table public.app_settings enable row level security;

-- The app writes through the service role from server-only route handlers.
-- Do not expose the service role key to the browser.

insert into storage.buckets (id, name, public)
values ('model-reference-photos', 'model-reference-photos', false)
on conflict (id) do nothing;
